[package]
name = "codedjimmy/netter"
description = "A Simple Networking Framework for games by T:Riza"
version = "0.0.1-alpha.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
BetterSignal = "codedjimmy/bettersignal@0.1.1"
Promise = "evaera/promise@4.0.0"