name: Publish

on:
  push:
    branches: [main]

jobs: 
  publish: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Wally Publish
        env:
          WALLY_AUTH: ${{ secrets.WALLY_AUTH }}
        run: |
          mv ./wally.toml ./src
          cd src
          mkdir ~/.wally
          printf "[tokens]\n\"https://api.wally.run/\" = \"%s\"" "$WALLY_AUTH" >> ~/.wally/auth.toml
          wally publish
          cd ..